### PR TITLE
Allow implicit conversion of dimensionless quantities to NumericalType

### PR DESCRIPTION
**Pull request by jplatte**
Okay, it's actually NumericType, without the al, but now I've already created the commit...

### CODE REVIEW

**Comment by fay59** [comment]
You can go back and `git commit --amend` ;) (or you can change NumericType to NumericalType in the code if you're confident that it's the right thing, English as a second language here, my first language has only one word for these two concepts)

If we go this way (and I think we should), it would be better to also make `raw()` private. This is because the raw quantity, taken alone, can be misleading. Say that I define `_g` instead of `_Kg`:

```
unit_base<units::gram> _g(1);
unit_base<units::gram> _Kg(1000);
auto _N = (_Kg * _m) / (_s * _s);
```

Now `_N` is `1000 * (_g * _m) / (_s * _s)`, so if I just use `newtons.raw()` on some Newton quantity, I get a value a thousand times larger than I would expect. However, if we make unitless quantities convertible to their underlying numeric(al?) type, we can say that the canonical way to get a raw number is to divide a quantity by its unit (`newtons / _N`), and now the problem disappears because we divide the numeric(al?) part by 1000 in the process.

**Comment by jplatte** [comment]
The problem with amending is that I can't push. I'm doing everything through the web UI at work because I happen to have logged in once. For pushing I'd need my push token, and I'd need it more than once. I'll just create new commits.

**Comment by jplatte** [comment]
About making `raw()` private: Why keep it at all then? You can just remove it.

**Comment by fay59** [comment]
I don't mind removing it either.

**Comment by jplatte** [comment]
When writing that last change, I found a bigger problem... But I think I should open a new issue for that, because I have two different ideas for fixing it and I'm not sure which one would be better.

**Comment by jplatte** [comment]
Oops, this doesn't compile yet. I'll have to make another quick change..

**Pull request merged**
